name: ✨ 기능 요청
description: 새로운 백엔드 기능 개발 요청을 등록합니다.
title: "[Feature] "
labels: [enhancement, backend]
body:
  - type: input
    id: summary
    attributes:
      label: 요약
      placeholder: '예: 사용자 탈퇴 기능 추가'

  - type: textarea
    id: details
    attributes:
      label: 상세 설명
      placeholder: 어떤 기능이며, 어떤 요구사항이 있는지 설명해주세요.
    validations:
      required: true

  - type: checkboxes
    id: scope
    attributes:
      label: 범위
      options:
        - label: API 개발 필요
        - label: DB 스키마 변경 필요
        - label: 인증/인가 관련
        - label: 외부 서비스 연동
