name: Deploy Spring Boot via systemd

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot App
        run: ./gradlew clean build -x test

      - name: Upload .jar to GCE VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          source: build/libs/*.jar
          target: /home/${{ secrets.GCE_USER }}/app/app.jar

      - name: Restart Spring Boot Service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            sudo systemctl restart springboot-app
            echo "Waiting for service..."
            sleep 5
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/actuator/health || true)
            if [ "$STATUS" = "200" ]; then
              echo "✅ Spring Boot is running."
              exit 0
            else
              echo "❌ Service failed to start properly. Status: $STATUS"
              sudo journalctl -u springboot-app --no-pager -n 20
              exit 1
            fi
